"""SceneJsonExecutor — turn user intent + context into a SceneSpec via LLM.

Flow:
  user_intent: "夏季清凉感、年轻女性、户外、克莱因蓝主色"
  + product_metadata: {"category": "apparel", "name": "Linen Dress"}
  + active_constraints: [{"no_text_in_image": True}, ...]
  + brand_kit (v2): {"colors": [...], "fonts": [...]}
       ↓
  LLM call (router.chat, response_format = SceneSpec json_schema)
       ↓
  SceneSpec instance (validated by Pydantic)

The LLM gets a system prompt explaining the schema and the constraints;
the user prompt is just the natural-language intent. We trust structured
output to deliver valid JSON — if it doesn't, that's `ModelInvalidResponse`
and the router retries / falls back.
"""

from __future__ import annotations

import json
import logging

from models.base import ChatMessage, ChatRequest
from models.cost import CostBudget
from models.exceptions import ModelInvalidResponse
from models.router import ModelRouter

from .schemas import Constraints, SceneSpec, scene_spec_json_schema

logger = logging.getLogger("listpack.scene_spec.executor")


SYSTEM_PROMPT = """\
You are ListPack's scene designer. The user describes what they want a
product image to look like; you reply with a SceneSpec JSON object that
the downstream image generator will render.

Hard rules:
- ALWAYS emit valid JSON conforming to the provided schema.
- Respect every constraint provided. If `no_text_in_image=true`, leave
  `text_overlays` empty AND don't put text in any element's `description`.
- If `background_must_be_white=true`, set background.type='solid'
  and background.value='#FFFFFF'.
- Be specific: pick a real colour palette (3-4 hex), real lighting, a
  real position for the product. The downstream renderer takes your
  spec literally.

Style guidance:
- For Amazon main images, set product.preserve_fidelity=true, scale≈0.87,
  and use a white background unless the user explicitly asks otherwise.
- For lifestyle / scene images, pick `background.type='scene'` with a
  short descriptive value (e.g. "summer beach golden hour").
- Keep `elements` to ≤3 — clutter hurts product perception.
"""


class SceneJsonExecutor:
    """Holds a Router reference + reusable system prompt."""

    def __init__(
        self,
        router: ModelRouter,
        *,
        model_hint: str | None = None,
        max_retries: int = 1,
    ) -> None:
        self._router = router
        self._model_hint = model_hint
        self._max_retries = max_retries

    async def generate(
        self,
        *,
        user_intent: str,
        product_metadata: dict | None = None,
        constraints: Constraints | None = None,
        brand_kit: dict | None = None,
        budget: CostBudget,
    ) -> SceneSpec:
        constraints = constraints or Constraints()
        user_msg = self._build_user_message(
            user_intent=user_intent,
            product_metadata=product_metadata or {},
            constraints=constraints,
            brand_kit=brand_kit,
        )

        req = ChatRequest(
            model="(router-chooses)",
            messages=[
                ChatMessage(role="system", content=SYSTEM_PROMPT),
                ChatMessage(role="user", content=user_msg),
            ],
            json_schema=scene_spec_json_schema(),
            temperature=0.4,
            max_tokens=1500,
        )

        last_err: Exception | None = None
        for attempt in range(self._max_retries + 1):
            try:
                resp = await self._router.chat(
                    req, budget=budget, model_hint=self._model_hint
                )
                # Router populates json_data when response_format is set,
                # but if a provider ignored it we fall back to text parsing.
                data = resp.json_data
                if data is None:
                    data = json.loads(resp.text)
                spec = SceneSpec.model_validate(data)
                logger.debug("scene spec generated by %s", resp.usage.model)
                return spec
            except (json.JSONDecodeError, ValueError) as exc:
                last_err = exc
                logger.warning(
                    "scene spec parse failed (attempt %d/%d): %s",
                    attempt + 1,
                    self._max_retries + 1,
                    exc,
                )
                # ask the next attempt to retry with stricter wording
                req.messages.append(
                    ChatMessage(
                        role="user",
                        content=(
                            "Your previous response did not parse as a valid "
                            "SceneSpec. Re-emit STRICT JSON conforming exactly "
                            "to the schema, with no commentary."
                        ),
                    )
                )

        raise ModelInvalidResponse(
            f"could not get valid SceneSpec after {self._max_retries + 1} attempts: {last_err}"
        )

    # ── prompt assembly ───────────────────────────────────────────

    @staticmethod
    def _build_user_message(
        *,
        user_intent: str,
        product_metadata: dict,
        constraints: Constraints,
        brand_kit: dict | None,
    ) -> str:
        lines = [
            f"User intent: {user_intent}",
            "",
            f"Product metadata: {json.dumps(product_metadata, ensure_ascii=False)}",
            "",
            f"Constraints (MUST be respected): {constraints.model_dump_json()}",
        ]
        if brand_kit:
            lines.extend(
                [
                    "",
                    f"Brand kit (use these colours/style when sensible): "
                    f"{json.dumps(brand_kit, ensure_ascii=False)}",
                ]
            )
        return "\n".join(lines)
